### ISSUE TITLE
usage question

### ISSUE THREAD

**Issue by joeblew99** [djherbis/bufdb#1]
this looks pretty cool, allong with NIO.

It can use boltdb under the hood.

I need to do streaming computation on data, and so the buffered approach looks like i might be able to encapsulate a server node, and us the buffering and boltdb backing to act as a queue, and do fan in and fan out style computation.

I am also looking at Transducers for creating standard compute logic that can be used with different data types. Because go does not have generics. This idea is copied from Elm and similar languages.

https://github.com/sdboyer/transducers-go

So my question is why did you make this and nio ?
Is it similar to my use case maybe ?

**Comment by djherbis** [comment]
Hey, thanks for your interest in this project!

**Is it similar to my use case**: If you want to do concurrent, byte-based processing with fan-outs I do have lots of libraries for doing this. I'd need more info on your requirements [non-blocking writes etc.] to answer more. Word of warning, generally speaking simpler is better. If you can accomplish what you want using the standard library, you'll probably be happier in the end. That being said, I do hope you find value in these libraries when appropriate. 

**Why did I make bufdb**: I originally created [buffer](https://github.com/djherbis/buffer) because I needed to do some very complicated buffering tricks. My client wanted to minimize the possibility of ever losing data, so whenever the application was signaled to shut down, it would freeze all the buffers and use bufdb to store them. On the next run, it'd reload all the buffers and continue processing.

**Why did I create nio**: I built nio because I had an incoming data stream that was being forked [via io.MultiWriter], each fork went into a [nio.Pipe](https://godoc.org/github.com/djherbis/nio#Pipe) wrapping an [buffer.NewUnboundedBuffer](https://godoc.org/github.com/djherbis/buffer#NewUnboundedBuffer). This was done so that each end of the buffered pipe got its own copy of the data to process, and could process it independently [one slow processor wouldn't block any other, because the slow one would just buffer more]. 

Two more libraries for doing **fan-outs**:

**[bufit](https://github.com/djherbis/bufit)** which lets you "fan-out" writes to a number of readers. No reader can be blocked by any other, but unlike the nio+unbounded buffer approach, all of the readers share an in-memory buffer. Also, after a section of the buffer is read by all readers, that section is dropped [readers who join at that point won't see the new data].

**[stream](https://github.com/djherbis/stream)** works similarly to bufit, except that it never drops data. Readers can always join and will always see a complete copy of the data until its "deleted". It also has configurable storage for the buffer (filesystem, in memory etc.).

**Comment by joeblew99** [comment]
it sounds like we are on the same page :)

The packages you have written look like useful tools for doing streaming computation infrastructure. By infrastructure i mean the fundamental lower level design properties to be able to build actual applications doing streaming computation. 
I used to use Spark and Kafka, and then various data stores underneath. Then i discovered apache samza and storm. All these are JVM . and so for me a show stopper.
There has to be a better way to do generalised streaming computation :)

My requirements:
At the moment i am needing to only do data analysis of the data coming in over the steam for two use cases:
1. Data coming in from CSV and needing to go through various stages of transformation, and down onto disk transformed.
- but the complications occur with holding the cognitive load in your head for the routines that stream from one into the other. So i want to build a way to visualise it. A bit like an IDE of computation as a web GUI, a bit like Cascading.
  http://www.cascading.org/driven/
1. Then there is the computation.
   Again in order to hold the cognitive load, you need to be able to visualsie what computation links with what, and so some sort of meta data about the computation is needed. It really only neeeds to declare what data sources are IN and OUT, and the computation given a name (in the namespace).
2. Then to visualise the data running through the nodes.
   Same thing again in that generic visualisers are built, and the meta data declares the visualise to use.
   The visualisers are like a Excel spreadsheet, and thats all they need to be, but unlike a spread sheet they need to of course have time and multiple matrixes (think Data Frames or Tensors)

The system can run in such a way that the probes that push to the GUI can be turned off of course and used on any CPU OS because its golang.

This is no easy task i know, but i have been building similar tools anyway because i have complex transformation computations running as batch at the moment. So the use cases are already tested and working, and its a matter of mapping it to t e streaming system.

In terms of Durable data, BoltDB Or LedisDB is a good start. Ledis DB has the advantage that is can use about 4 or 5 different databases, but has a single API, and so you can choose the storage medium based on the exact computation type ( read heavy of write heavy).

The other question is data structures that join the computations. SPark uses RDD, but recently DataSet. DataSets are exactly the same as what i know from the c# world.
http://spark.apache.org/docs/latest/sql-programming-guide.html
These are just generalised data structures, but it will be interesting to see what you think about these in terms of buffering and channels.

**Comment by joeblew99** [comment]
You have allot of packages that represent the building blocks, but no examples of their usage in each.
i only looked at the stream (https://github.com/djherbis/stream) one so far just now.
Is there a higher level repo that uses these, so i can get a sense of usage ?

**Comment by joeblew99** [comment]
Just realised that what LedisDB represents might be a good marriage for your stuff.
LedisDB is pretty cool because it slims down the data structures down to a small set of simple ones. But there are enough that they can be used for many different problems.
But Ledis does not have any of the concepts of streaming between the computations nodes.
LedisDB also holds that all computation can work in RAM and spill over to Disk if needed. Its one of its Tenants, which is the right one for this area.

Its also been used in Anger a fair bit.
https://godoc.org/github.com/siddontang/ledisdb/ledis?importers

**Comment by djherbis** [comment]
Looks like I have a lot to respond to! I'll try and break it down to answer each of your posts:

**1. What do I think about the various libs you mentioned.** 
There's a lot going on there. It sounds like you have a cool idea (I've actually thought of something similar myself for visualizing network streams). I can't really comment on exactly what technologies you should use to solve this problem though, there are lots of other questions that you'll have to work through to see which ones are the best fit for you. First and foremost, I suggest starting with the standard Go library, and the simplest dependencies that you require to get something working. Try wrapping your dependencies in structs/interfaces that describe how they "couple" with your application. That way, it won't be too hard to switch them out if/when necessary. Don't overthink the technical parts of the design right off the bat, sometimes prototyping (with loose coupling) can really help to discern the right tool/lib for the job.

**2. Is there a higher level repo that has example usage of my repos?**
This is a great question, I should probably add some an example tools to each of my libraries so people can get a real idea of what they can be used for.

One sample user for stream is [taskcluster-worker](https://github.com/taskcluster/taskcluster-worker/blob/dc0f6a01639dfa39264227a61e8ffdb87e6cb642/runtime/taskcontext.go), it looks like they use stream for streaming log files for their jobs.

**3. LedisDB and my libs**
I haven't personally worked with LedisDB, if you do give it a shot, maybe let me know if there were any pain points in integrating with my libs so I can consider some improvements. Other than that, you can always open an issue on a particular lib and put up some sample code to ask if it looks like you're using the lib right.

Hope that helps! Sorry that I can't give you direct answers to some of your questions, but I hope this gives you some direction.

**Comment by joeblew99** [comment]
That's for your thoughts - its really useful to see your opinions.

One big thing in all of this is how to do computation on data that not
relying on SQL, so that users get back the power to incorporate task and
data parallelism without being locked into a dB doing it for them.
Basically you have a nice big wide data lake of data and you want to do
thing like sorting, grouping, filtering on the data.

The simple stow package is a good example. What would really help are utils
for doing these SQL like operations on that data. I am currently looking
around the these type of classic routines.
It's a small step but very useful for me to get going.
It's also very useful on current projects I have.

Then after these base operations are done, these joining them up using the
buffering libraries.

So if you happen to know any libraries with generalised sorting and
grouping shout :)

Cheers
